spring:
  datasource:
      username: root
      password: shitou19990225
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/youxue?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 0
    lettuce:
      shutdown-timeout: 3000ms

  file:
    path: F:/files
    url: http://localhost:8080/files
